/**
 * LESSON 04-crud/01-create — Creating documents
 *
 * Every way to get data INTO MongoDB through Mongoose: `create()` (one doc
 * and many), `insertMany()` (one bulk command, including what happens when
 * part of the batch fails), and the native driver's `insertOne` — so you can
 * see exactly which safety rails Mongoose adds on top of raw MongoDB.
 *
 * SAFETY: every document this lesson writes is a TEMPORARY practice doc,
 * marked by email `...@lesson.test` or SKU `ZZ-...`. They are swept away at
 * the start (in case a previous run crashed) and again at the end. Seeded
 * data is never touched.
 *
 * Run it with:  npm run lesson 04-crud/01-create
 */
import mongoose from "mongoose";
import { runLesson, section, show, note } from "../../lib/lesson-runner.js";
import User from "../../../models/user.model.js";
import Product from "../../../models/product.model.js";
import Category from "../../../models/category.model.js";

// Temp-data markers shared by the whole bootcamp: any user email ending in
// @lesson.test and any product SKU starting with ZZ- is a practice doc.
const TEMP_EMAIL = /@lesson\.test$/i;
const TEMP_SKU = /^ZZ-/;

/**
 * DESTRUCTIVE — but only for practice docs matching the temp markers above.
 * Called before the lesson (a crashed earlier run may have left leftovers)
 * and after it (so the database ends exactly as it started).
 */
async function removeTempDocs() {
  const users = await User.deleteMany({ email: TEMP_EMAIL });
  const products = await Product.deleteMany({ sku: TEMP_SKU });
  return {
    tempUsersRemoved: users.deletedCount,
    tempProductsRemoved: products.deletedCount,
  };
}

await runLesson("CRUD 1/4 — Creating documents", async () => {
  section("0. Safety sweep — remove practice docs a crashed run left behind");
  show("Leftovers removed (0 is normal)", await removeTempDocs());

  try {
    // ------------------------------------------------------------------
    section("1. Model.create(doc) — one document, the full treatment");
    // create() is the "everything included" insert. Before anything reaches
    // MongoDB, Mongoose (in Node.js!) casts types, runs setters (trim,
    // lowercase...), fills defaults, and runs every validator. Only then is
    // ONE insertOne command sent to the server.
    const prem = await User.create({
      name: "  Prem Lessondemo  ", // extra spaces on purpose — watch `trim`
      email: "Prem.Creator@LESSON.TEST", // uppercase on purpose — watch `lowercase`
      age: 28,
      interests: ["reading", "yoga"],
      address: { street: "12 MG Road", city: "Pune", state: "Maharashtra", zip: "411001" },
    });
    show("The document create() returned", prem.toObject());
    note(
      "Things to spot: name was trimmed, email was lowercased (setters ran); " +
        "role/isActive/loyaltyPoints/deletedAt were filled from schema DEFAULTS; " +
        "createdAt/updatedAt came from the timestamps option; and _id was " +
        "generated by Mongoose in Node BEFORE the server ever saw the doc — " +
        "ObjectIds are made client-side, no round trip needed."
    );

    // ------------------------------------------------------------------
    section("2. Validation happens in Node — an invalid doc never leaves the app");
    // age has `min: [13, ...]` in the schema. create() runs that validator
    // BEFORE talking to MongoDB, so the insert below fails without any
    // network write. This is Mongoose behavior, not a database rule.
    try {
      await User.create({ name: "Too Young", email: "too.young@lesson.test", age: 9 });
    } catch (error) {
      show("Error type", error.name); // ValidationError
      show("Field-level message", error.errors?.age?.message);
    }
    // exists() returns { _id } when a match exists, null when it doesn't —
    // perfect for a quick "did that insert happen?" check.
    show(
      "Was the invalid user inserted? (null = no)",
      await User.exists({ email: "too.young@lesson.test" })
    );
    note(
      "MongoDB itself would have accepted { age: 9 } happily — it knows " +
        "nothing about the schema. Validation is a Mongoose (application-side) " +
        "safety rail. Only the unique index on email is enforced by the server."
    );

    // ------------------------------------------------------------------
    section("3. Model.create([docs]) — array in, array out");
    // Same method, array form: each element gets the FULL create() pipeline
    // (setters, defaults, validators, save middleware), and Mongoose issues
    // one insert per document. Convenient, but N documents = N writes.
    const testers = await User.create([
      { name: "Bina Batchdemo", email: "batch.one@lesson.test", age: 34 },
      { name: "Chetan Batchdemo", email: "batch.two@lesson.test" },
    ]);
    show(
      "create([]) returned an ARRAY of documents",
      testers.map((u) => ({ name: u.name, email: u.email, role: u.role, _id: u._id }))
    );
    note(
      "One doc in -> one doc out; array in -> array out. If one element fails " +
        "validation, create() rejects — but elements already saved are NOT " +
        "rolled back. Inserts are not a transaction (module 14 covers those)."
    );

    // ------------------------------------------------------------------
    section("4. Model.insertMany(docs) — one bulk command for the whole batch");
    // Products require a category ObjectId, so borrow a seeded category.
    const laptops = await Category.findOne({ slug: "laptops" });
    if (!laptops) throw new Error("Seeded data missing — run: npm run db:seed");

    // insertMany sends the whole batch as ONE insertMany command — one round
    // trip instead of N. Mongoose still casts + validates every doc and
    // applies timestamps, but document middleware (pre/post 'save') does NOT
    // run — only pre('insertMany') hooks would.
    const accessories = await Product.insertMany([
      // sku typed lowercase on purpose — the uppercase setter still runs.
      { name: "ZZ Practice Laptop Sleeve", sku: "zz-crud-1001", price: 1499, stock: 40, category: laptops._id, tags: ["budget"], specs: { brand: "Volt", color: "grey" } },
      { name: "ZZ Practice Laptop Stand", sku: "zz-crud-1002", price: 2499, stock: 25, category: laptops._id, tags: ["new-arrival"], specs: { brand: "Nexa", color: "silver" } },
      { name: "ZZ Practice USB-C Dock", sku: "zz-crud-1003", price: 5999, stock: 12, category: laptops._id, tags: ["premium"], specs: { brand: "Orbit", color: "black" } },
    ]);
    show(
      "insertMany() returned",
      accessories.map((p) => ({ sku: p.sku, name: p.name, createdAt: p.createdAt }))
    );
    note(
      "All three SKUs are uppercase (setters ran) and timestamps exist. " +
        "Rule of thumb: importing/bulk-loading -> insertMany (fast, one " +
        "command); normal app writes -> create()/save() (full middleware)."
    );

    // ------------------------------------------------------------------
    section("5. Partial failure with ordered: true (the default)");
    // ordered:true means MongoDB inserts docs IN ORDER and STOPS at the
    // first error. Everything before the bad doc stays inserted — there is
    // NO rollback. Here doc #2 reuses doc #1's SKU, so the unique index on
    // sku (a real DATABASE rule) rejects it with error code 11000.
    try {
      await Product.insertMany([
        { name: "ZZ Practice Mouse A", sku: "ZZ-ORD-0001", price: 899, stock: 30, category: laptops._id },
        { name: "ZZ Practice Mouse B", sku: "ZZ-ORD-0001", price: 999, stock: 30, category: laptops._id }, // duplicate!
        { name: "ZZ Practice Mouse C", sku: "ZZ-ORD-0002", price: 1099, stock: 30, category: laptops._id },
      ]);
    } catch (error) {
      show("insertMany threw", error.name); // MongoBulkWriteError
      show("Write errors in the batch", error.writeErrors?.length);
    }
    show(
      "How many ZZ-ORD- docs actually landed?",
      await Product.countDocuments({ sku: /^ZZ-ORD-/ })
    );
    note(
      "Expected count: 1. Doc #1 was inserted, #2 failed on the unique sku " +
        "index, #3 was NEVER ATTEMPTED. An error being thrown does not mean " +
        "nothing was written — a classic bulk-import surprise."
    );

    // ------------------------------------------------------------------
    section("6. ordered: false — attempt every doc, report all failures at the end");
    // With ordered:false MongoDB keeps going past errors: every valid doc is
    // inserted, and ONE error is thrown afterwards summarizing the failures.
    try {
      await Product.insertMany(
        [
          { name: "ZZ Practice Keyboard A", sku: "ZZ-UNO-0001", price: 1899, stock: 20, category: laptops._id },
          { name: "ZZ Practice Keyboard B", sku: "ZZ-UNO-0002", price: 2199, stock: 20, category: laptops._id },
          { name: "ZZ Practice Keyboard C", sku: "ZZ-UNO-0001", price: 2399, stock: 20, category: laptops._id }, // duplicate!
          { name: "ZZ Practice Keyboard D", sku: "ZZ-UNO-0003", price: 2599, stock: 20, category: laptops._id },
        ],
        { ordered: false }
      );
    } catch (error) {
      show("Failures reported", error.writeErrors?.length); // 1
      // Mongoose attaches the docs that DID make it to the error object.
      show("Docs that were still inserted", error.insertedDocs?.length); // 3
    }
    show(
      "How many ZZ-UNO- docs actually landed?",
      await Product.countDocuments({ sku: /^ZZ-UNO-/ })
    );
    note(
      "Expected count: 3 — the duplicate was skipped, the docs AFTER it were " +
        "still inserted. Use ordered:false for imports where one bad row " +
        "must not block the rest; then read error.writeErrors to log what failed."
    );

    // ------------------------------------------------------------------
    section("7. The native driver's insertOne — what MongoDB does WITHOUT Mongoose");
    // mongoose.connection.db is the raw MongoDB driver database handle on
    // the SAME open connection. Talking to it skips Mongoose entirely:
    // no casting, no setters, no defaults, no validators, no timestamps.
    const rawUsers = mongoose.connection.db.collection("users");
    const driverResult = await rawUsers.insertOne({
      name: "Raw Driverdemo",
      email: "raw.driver@lesson.test", // still temp-marked, so cleanup finds it
      role: "customer",
    });
    show("Driver result (no document — just an acknowledgement)", driverResult);

    // Read it back with the raw driver too, so we see EXACTLY what is stored.
    const storedRaw = await rawUsers.findOne({ email: "raw.driver@lesson.test" });
    show("What MongoDB actually stored", storedRaw);
    note(
      "Compare with section 1: no isActive, no loyaltyPoints, no interests, " +
        "no deletedAt, no createdAt/updatedAt — MongoDB stores exactly what it " +
        "was sent and enforces NOTHING from the schema. Every rail you saw " +
        "earlier lives in Mongoose, in your Node process. (Careful: reading " +
        "this doc back THROUGH the model would fill defaults in memory and " +
        "hide the gaps.) This is why app code should always go through models."
    );
  } finally {
    // finally-block cleanup: runs even if a section above threw, so no
    // practice doc can outlive the lesson.
    section("Cleanup — DESTRUCTIVE, but only for @lesson.test / ZZ- practice docs");
    show("Removed", await removeTempDocs());
    note("The database is back to exactly its seeded state.");
  }
});
